# Generated by Django 6.0.1 on 2026-04-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('email', models.TextField()),
                ('user_level', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
