# Generated by Django 6.0.1 on 2026-04-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='firstName',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastName',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(),
        ),
    ]
