# Generated by Django 6.0.1 on 2026-04-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_created_at_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator')], default='moderator', max_length=20),
        ),
    ]
