# Generated by Django 6.0.1 on 2026-04-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_level',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
