# Generated by Django 6.0.1 on 2026-04-23 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0008_itemdetails_poster_contact_itemdetails_poster_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=30)),
                ('claimant_contact', models.CharField(max_length=30)),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
                ('proof_description', models.TextField(default='', max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemdetails')),
            ],
        ),
    ]
