# Generated by Django 6.0.1 on 2026-04-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_item_name', models.CharField(max_length=30)),
                ('found_item_category', models.CharField(choices=[('ALL', 'All'), ('PERSONAL', 'Personal'), ('ACCESSORIES', 'Accessories'), ('ID', 'id'), ('ELECTRONICS', 'Electronics'), ('KEYS', 'Keys'), ('VALUABLES', 'Valuables')], default='ALL', max_length=30)),
                ('found_item_location', models.CharField(choices=[('ALL', 'All'), ('CANTEEN', 'Canteen'), ('GYM', 'Gym'), ('HS_GROUNDS', 'Highschool Grounds'), ('BASEMENT', 'Basement'), ('MAIN_BLDG', 'Main Building'), ('SAO_LOBBY', 'Sao Lobby'), ('PARKING_AREA', 'Parking Area')], default='ALL', max_length=30)),
                ('found_item_date_and_time', models.DateTimeField(max_length=15)),
                ('found_item_image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('found_item_status', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LostItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_item_name', models.CharField(max_length=30)),
                ('lost_item_category', models.CharField(choices=[('ALL', 'All'), ('PERSONAL', 'Personal'), ('ACCESSORIES', 'Accessories'), ('ID', 'id'), ('ELECTRONICS', 'Electronics'), ('KEYS', 'Keys'), ('VALUABLES', 'Valuables')], default='ALL', max_length=30)),
                ('lost_item_location', models.CharField(choices=[('ALL', 'All'), ('CANTEEN', 'Canteen'), ('GYM', 'Gym'), ('HS_GROUNDS', 'Highschool Grounds'), ('BASEMENT', 'Basement'), ('MAIN_BLDG', 'Main Building'), ('SAO_LOBBY', 'Sao Lobby'), ('PARKING_AREA', 'Parking Area')], default='ALL', max_length=30)),
                ('lost_item_date_and_time', models.DateTimeField(max_length=15)),
                ('lost_item_image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('lost_item_status', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=5)),
            ],
        ),
    ]
