# Generated by Django 6.0.1 on 2026-04-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LostItemDetails',
            new_name='ItemDetails',
        ),
        migrations.DeleteModel(
            name='FoundItemDetails',
        ),
        migrations.RenameField(
            model_name='itemdetails',
            old_name='lost_item_category',
            new_name='item_category',
        ),
        migrations.RenameField(
            model_name='itemdetails',
            old_name='lost_item_date_and_time',
            new_name='item_date_and_time',
        ),
        migrations.RenameField(
            model_name='itemdetails',
            old_name='lost_item_image',
            new_name='item_image',
        ),
        migrations.RenameField(
            model_name='itemdetails',
            old_name='lost_item_location',
            new_name='item_location',
        ),
        migrations.RenameField(
            model_name='itemdetails',
            old_name='lost_item_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='itemdetails',
            old_name='lost_item_status',
            new_name='item_status',
        ),
    ]
