# Generated by Django 6.0.1 on 2026-04-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_lostitemdetails_itemdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='items_photos/'),
        ),
    ]
