# Generated by Django 6.0.1 on 2026-04-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_itemdetails_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='item_category',
            field=models.CharField(choices=[('ALL', 'All'), ('PERSONAL', 'Personal'), ('ACCESSORIES', 'Accessories'), ('ID', 'Id'), ('ELECTRONICS', 'Electronics'), ('KEYS', 'Keys'), ('VALUABLES', 'Valuables')], default='ALL', max_length=30),
        ),
    ]
