# Generated by Django 6.0.1 on 2026-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_itemdetails_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='declinedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_category', models.CharField(max_length=30)),
                ('item_location', models.CharField(max_length=30)),
                ('item_date_and_time', models.DateTimeField(max_length=15)),
                ('item_status', models.CharField(max_length=5)),
            ],
        ),
    ]
