# Generated by Django 6.0.1 on 2026-04-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_declineditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='declineditems',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='declined_items_photos/'),
        ),
    ]
