# Generated by Django 6.0.1 on 2026-04-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_declineditems_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetails',
            old_name='item_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='itemdetails',
            old_name='item_date_and_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='itemdetails',
            old_name='item_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='itemdetails',
            old_name='item_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='itemdetails',
            old_name='item_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='item_status',
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CLAIMED', 'Claimed'), ('RETURNED', 'Returned'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=30),
        ),
    ]
