# Generated by Django 6.0.1 on 2026-04-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_rename_item_category_itemdetails_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='poster_contact',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='poster_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
